name: engineer_ai

description: Engineering AI Operator

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.13.0
  flutter_blue_plus: ^1.32.8
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
